type AboutPageKey = "overview" | "model" | "impact" | "stories" | "governance";

const pageContent: Record<AboutPageKey, { title: string; description: string; eyebrow: string; heading: string; intro: string; body: string }> = {
  overview: {
    title: "About TuHiTu Club | Adopt an Elder",
    description: "Learn why TuHiTu Club exists, the values guiding its Adopt an Elder initiative and how it brings elders, volunteers and community organisations together.",
    eyebrow: "About TuHiTu Club",
    heading: "A community built so no elder feels forgotten.",
    intro: "TuHiTu Club is an initiative by the Federation of Digital Health Sciences (FDHS), created to make safe, regular companionship easier to organise across generations.",
    body: `
      <section class="section-pad about-story-section"><div class="container about-split"><div class="section-head reveal"><span class="eyebrow">Why We Exist</span><h2>Care can be present while companionship is still missing.</h2><p>Families, care teams and communities can do everything possible and an elder may still experience long stretches without a meaningful one-to-one conversation. TuHiTu Club exists to add that human connection—not to replace family, clinical care or professional support.</p><p>The programme prepares volunteers, works with care organisations and coordinates consent-led companionship through calls, letters, approved visits and community experiences.</p></div><div class="about-image-card reveal"><img src="/images/mission-companionship.webp" alt="An elder and a young volunteer walking and talking in a garden" width="1120" height="1400"><div><strong>One relationship at a time</strong><span>Listening, consistency and dignity before scale.</span></div></div></div></section>
      <section class="belief-statement about-belief"><div class="container"><blockquote class="reveal"><span class="quote-mark" aria-hidden="true">&ldquo;</span><p><span class="belief-prefix">True service begins with</span><strong class="satya-focus">Satya</strong><span class="belief-copy">— the truth that every elder deserves love, dignity and belonging. Guided by Satya, inspired by Seva and driven by Samman, TuHiTu Club works to make sure no elder feels forgotten.</span></p></blockquote></div></section>
      <section class="section-pad about-values"><div class="container"><div class="section-head center reveal"><span class="eyebrow">What Guides Us</span><h2>Three values. One standard of care.</h2></div><div class="value-grid reveal-stagger reveal"><article><span>01</span><h3>Satya · Truth</h3><p>Clear claims, honest expectations and no invented proof. What is planned, active and completed should never be confused.</p></article><article><span>02</span><h3>Seva · Service</h3><p>Practical contribution centred on the elder’s preferences—not the volunteer’s need for recognition.</p></article><article><span>03</span><h3>Samman · Dignity</h3><p>Consent, privacy and respect in every story, image, match and programme decision.</p></article></div></div></section>
      <section class="about-cta-band"><div class="container"><div><span class="eyebrow">Choose Your Role</span><h2>There is more than one way to help.</h2></div><div class="about-cta-links"><a class="btn btn-primary" href="/volunteer">Companion</a><a class="btn btn-ghost" href="/care-homes">Register a Care Home</a><a class="btn btn-ghost" href="/sponsor">Sponsor a Programme</a></div></div></section>`,
  },
  model: {
    title: "Our Mission & Model | TuHiTu Club",
    description: "See how TuHiTu Club reviews, prepares, matches and supports volunteers, elders and participating care organisations.",
    eyebrow: "Our Mission & Model",
    heading: "Kindness becomes dependable when the process is clear.",
    intro: "TuHiTu Club turns good intent into a supported relationship through review, consent, careful matching and ongoing coordination.",
    body: `
      <section class="section-pad process-section"><div class="container"><div class="section-head center reveal"><span class="eyebrow">The Programme Path</span><h2>From registration to a sustained connection</h2></div><ol class="process-grid five-step-grid reveal-stagger reveal"><li class="process-card"><span class="process-number">01</span><h3>Register</h3><p>Volunteers and organisations share only the information needed for first-stage review.</p></li><li class="process-card"><span class="process-number">02</span><h3>Review</h3><p>TuHiTu Club checks suitability, readiness and the appropriate safeguarding path.</p></li><li class="process-card"><span class="process-number">03</span><h3>Prepare</h3><p>Participants understand boundaries, responsibilities and escalation routes.</p></li><li class="process-card"><span class="process-number">04</span><h3>Match</h3><p>Consent, language, interests, location and availability guide each introduction.</p></li><li class="process-card"><span class="process-number">05</span><h3>Support</h3><p>Coordinators follow up, document activity and respond when a relationship needs help or change.</p></li></ol></div></section>
      <section class="section-pad model-roles"><div class="container"><div class="section-head center reveal"><span class="eyebrow">Shared Responsibility</span><h2>Everyone has a clear role</h2></div><div class="roles-grid reveal-stagger reveal"><article class="role-card"><div class="role-card-head"><div class="icon-circle amber"><i class="fa-solid fa-person-cane"></i></div><div><span class="mini-label">The Elder</span><h3>Chooses whether and how to participate</h3></div></div><ul class="check-list"><li><i class="fa-solid fa-circle-check"></i><span>Gives informed consent</span></li><li><i class="fa-solid fa-circle-check"></i><span>Shares preferences and boundaries</span></li><li><i class="fa-solid fa-circle-check"></i><span>Can pause or end participation</span></li></ul></article><article class="role-card"><div class="role-card-head"><div class="icon-circle navy"><i class="fa-solid fa-user-group"></i></div><div><span class="mini-label">The Companion</span><h3>Shows up reliably within programme boundaries</h3></div></div><ul class="check-list"><li><i class="fa-solid fa-circle-check"></i><span>Completes required preparation</span></li><li><i class="fa-solid fa-circle-check"></i><span>Maintains respectful, regular contact</span></li><li><i class="fa-solid fa-circle-check"></i><span>Raises concerns through the coordinator</span></li></ul></article><article class="role-card"><div class="role-card-head"><div class="icon-circle green"><i class="fa-solid fa-house-chimney-medical"></i></div><div><span class="mini-label">The Care Organisation</span><h3>Supports consent, scheduling and resident wellbeing</h3></div></div><ul class="check-list"><li><i class="fa-solid fa-circle-check"></i><span>Names an accountable coordinator</span></li><li><i class="fa-solid fa-circle-check"></i><span>Supports resident-level consent</span></li><li><i class="fa-solid fa-circle-check"></i><span>Escalates safeguarding issues promptly</span></li></ul></article><article class="role-card"><div class="role-card-head"><div class="icon-circle rust"><i class="fa-solid fa-hand-holding-heart"></i></div><div><span class="mini-label">TuHiTu Club</span><h3>Sets standards and coordinates the relationship</h3></div></div><ul class="check-list"><li><i class="fa-solid fa-circle-check"></i><span>Reviews and prepares participants</span></li><li><i class="fa-solid fa-circle-check"></i><span>Supports matching and follow-up</span></li><li><i class="fa-solid fa-circle-check"></i><span>Maintains grievance and safeguarding routes</span></li></ul></article></div></div></section>
      <section class="evidence-section section-pad"><div class="dot-grid"></div><div class="container evidence-grid"><div class="section-head reveal"><span class="eyebrow">What TuHiTu Club Is Not</span><h2>Clear boundaries protect everyone.</h2><p>Companionship should never be confused with professional care, crisis support or financial assistance.</p></div><div class="evidence-card reveal"><ul class="check-list"><li><i class="fa-solid fa-xmark"></i><span>Not a clinical, counselling or emergency service</span></li><li><i class="fa-solid fa-xmark"></i><span>Not a route to borrow, lend or transfer money between participants</span></li><li><i class="fa-solid fa-xmark"></i><span>Not direct, unsupervised access to elders after an online form</span></li><li><i class="fa-solid fa-xmark"></i><span>Not permission to publish resident stories or images without consent</span></li></ul></div><aside class="reporting-card reveal"><span class="mini-label">Ready To Join?</span><h3>Choose the pathway that fits your role.</h3><p><a class="inline-link" href="/volunteer">Companion</a> · <a class="inline-link" href="/care-homes">Care Homes</a> · <a class="inline-link" href="/partner-with-us">Community Partners</a></p></aside></div></section>`,
  },
  impact: {
    title: "Impact & Reach | TuHiTu Club",
    description: "Review TuHiTu Club's association and registration figures, programme reach and the outcome measures it intends to report responsibly.",
    eyebrow: "Impact & Reach",
    heading: "Growth matters only when it becomes a better elder experience.",
    intro: "TuHiTu Club separates network-scale figures from completed programme outcomes so supporters can understand what each number actually represents.",
    body: `
      <section class="section-pad impact-page-stats"><div class="container"><div class="section-head center reveal"><span class="eyebrow">Current Association Figures</span><h2>The network around the mission</h2><p>These organisation-provided figures describe association, registration and activity in process. They are not presented as audited completed matches or independently verified outcomes.</p></div><div class="impact-grid reveal-stagger reveal"><div class="impact-card"><i class="fa-solid fa-user-group"></i><div class="num" data-count="12400">0</div><div class="label">Elders associated</div></div><div class="impact-card"><i class="fa-solid fa-earth-americas"></i><div class="num" data-count="18">0</div><div class="label">Countries with associated partners</div></div><div class="impact-card"><i class="fa-solid fa-hand-holding-heart"></i><div class="num" data-count="9600">0</div><div class="label">Registered volunteers</div></div><div class="impact-card"><i class="fa-solid fa-phone-volume"></i><div class="num" data-count="150000">0</div><div class="label">Calls &amp; visits in process</div></div></div></div></section>
      <section class="section-pad measurement-section"><div class="container"><div class="section-head center reveal"><span class="eyebrow">How Impact Should Be Measured</span><h2>Beyond registrations and reach</h2><p>TuHiTu Club’s reporting framework should move from activity to relationship quality and elder experience.</p></div><div class="measurement-grid reveal-stagger reveal"><article><span>01</span><h3>Reach</h3><p>Approved elders, active volunteers, participating facilities and supported geographies.</p></article><article><span>02</span><h3>Engagement</h3><p>Completed calls, letters, visits, match continuity and volunteer retention.</p></article><article><span>03</span><h3>Experience</h3><p>Elder, family and care-team feedback on dignity, belonging and anticipation.</p></article><article><span>04</span><h3>Safety</h3><p>Orientation completion, concerns raised, response time and resolution quality.</p></article></div></div></section>
      <section class="about-cta-band"><div class="container"><div><span class="eyebrow">Evidence Before Claims</span><h2>Support transparent programme reporting.</h2><p>Organisations can sponsor defined work with agreed reporting; volunteers help turn registrations into sustained relationships.</p></div><div class="about-cta-links"><a class="btn btn-primary" href="/sponsor">Sponsor With Reporting</a><a class="btn btn-ghost" href="/volunteer">Companion</a></div></div></section>`,
  },
  stories: {
    title: "Stories & Updates | TuHiTu Club",
    description: "Read TuHiTu Club programme notes about elder companionship, volunteer readiness and responsible community partnerships.",
    eyebrow: "Stories & Updates",
    heading: "The work becomes real in the conversations people choose to continue.",
    intro: "Until consented participant stories and verified programme updates are ready, TuHiTu Club publishes practical programme notes—not fictional testimonials.",
    body: `
      <section class="section-pad stories-page"><div class="container"><div class="news-grid reveal-stagger reveal"><article class="news-card"><div class="news-thumb"><img src="/images/community-stories.webp" alt="Elders and companions sharing stories" width="1584" height="990"><span class="news-tag">Why It Matters</span></div><div class="news-body"><div class="news-date"><i class="fa-solid fa-book-open"></i> Programme Note</div><h3>Why a regular conversation can matter</h3><p>Consistency, listening and belonging can give an elder something personal to anticipate.</p><a href="/?content=story-one" class="news-link">Read the note <i class="fa-solid fa-arrow-right"></i></a></div></article><article class="news-card"><div class="news-thumb"><img src="/images/news-letter-exchange.webp" alt="An elder and companion sharing a letter" width="1584" height="990"><span class="news-tag">Companion Readiness</span></div><div class="news-body"><div class="news-date"><i class="fa-solid fa-book-open"></i> Programme Note</div><h3>Good intentions need preparation</h3><p>Review, orientation, boundaries and a clear support route come before matching.</p><a href="/?content=story-two" class="news-link">Read the note <i class="fa-solid fa-arrow-right"></i></a></div></article><article class="news-card"><div class="news-thumb"><img src="/images/news-community-partnership.webp" alt="A community coordinator with elders and companions" width="1584" height="990"><span class="news-tag">Partnerships</span></div><div class="news-body"><div class="news-date"><i class="fa-solid fa-book-open"></i> Programme Note</div><h3>How organisations can introduce TuHiTu Club safely</h3><p>A named coordinator, consent process and shared responsibilities protect every participant.</p><a href="/?content=story-three" class="news-link">Read the note <i class="fa-solid fa-arrow-right"></i></a></div></article></div></div></section>
      <section class="story-standards section-pad"><div class="container about-split"><div class="section-head reveal"><span class="eyebrow">Story Standards</span><h2>No dignity should be traded for engagement.</h2><p>Future stories should use explicit consent, avoid unnecessary health details, protect identity where appropriate and never imply that an elder is helpless to make a donation or volunteer conversion easier.</p></div><div class="family-promise-card reveal"><h3>Before a story is published</h3><ul class="check-list"><li><i class="fa-solid fa-circle-check"></i><span>Consent and approval are documented</span></li><li><i class="fa-solid fa-circle-check"></i><span>The elder’s voice and preferences remain central</span></li><li><i class="fa-solid fa-circle-check"></i><span>Claims and outcomes are verified</span></li><li><i class="fa-solid fa-circle-check"></i><span>Sensitive information is removed</span></li></ul></div></div></section>`,
  },
  governance: {
    title: "Governance & Safeguarding | TuHiTu Club",
    description: "Review TuHiTu Club's safeguarding, privacy, donation, grievance and programme-governance commitments.",
    eyebrow: "Governance & Safeguarding",
    heading: "Trust is a system, not a badge.",
    intro: "TuHiTu Club is building a clear operating framework for safeguarding, privacy, donations, partner approval and complaints before programme scale.",
    body: `
      <section class="section-pad governance-page"><div class="container governance-grid">
        <article class="governance-card reveal" id="safeguarding"><div class="icon-circle amber"><i class="fa-solid fa-shield-heart"></i></div><h2>Safeguarding</h2><p>Online registration does not create direct access to an elder. Required review, verification, orientation, consent and coordination come first.</p><ul><li>Defined participant boundaries</li><li>Named escalation and coordinator roles</li><li>Prompt response to concerns</li><li>Ability to pause or end participation</li></ul></article>
        <article class="governance-card reveal" id="privacy"><div class="icon-circle navy"><i class="fa-solid fa-lock"></i></div><h2>Privacy & Data</h2><p>Website forms collect only the information needed to respond, review and coordinate the stated request.</p><ul><li>No card, UPI PIN or online-banking credentials stored by TuHiTu Club</li><li>No resident medical or identity documents in first-stage forms</li><li>Requests to correct or delete submitted information accepted at connect@tuhitu.org</li><li>Consent does not permit unrelated marketing</li></ul></article>
        <article class="governance-card reveal" id="donations"><div class="icon-circle green"><i class="fa-solid fa-hand-holding-dollar"></i></div><h2>Donations & 80G</h2><p>Payments are handed to the authorised gateway. Eligible Indian donations may qualify for an 80G deduction, subject to applicable law and issuance of a valid receipt.</p><ul><li>One-time and recurring options depend on gateway availability</li><li>Fund use follows approved programme priorities and donor restrictions where accepted</li><li>International donors should seek advice in their own jurisdiction</li><li>Refund, duplicate and failed-payment queries are reviewed against gateway records</li></ul></article>
        <article class="governance-card reveal" id="grievance"><div class="icon-circle rust"><i class="fa-solid fa-scale-balanced"></i></div><h2>Grievance & Complaints</h2><p>Raise concerns about safeguarding, data, volunteering, payments, partnerships or care-home participation through the official contact details below.</p><ul><li>Email connect@tuhitu.org</li><li>Call +91 95996 61292</li><li>Include the relevant reference number where available</li><li>Mark urgent safeguarding concerns clearly</li></ul></article>
      </div></section>
      <section class="evidence-section section-pad"><div class="dot-grid"></div><div class="container evidence-grid"><div class="section-head reveal"><span class="eyebrow">Governance Position</span><h2>An initiative by FDHS.</h2><p>TuHiTu Club is presented as an initiative of the Federation of Digital Health Sciences. Programme approvals, public claims, partner listings and financial support should remain traceable to authorised records.</p></div><div class="evidence-card reveal"><h3>Operational controls</h3><ul class="check-list"><li><i class="fa-solid fa-file-signature"></i><span>Documented roles and approval authority</span></li><li><i class="fa-solid fa-building-shield"></i><span>Due diligence for care homes and organisations</span></li><li><i class="fa-solid fa-receipt"></i><span>Payment and receipt reconciliation</span></li><li><i class="fa-solid fa-chart-line"></i><span>Claims separated into targets, registrations, activity and verified outcomes</span></li></ul></div><aside class="reporting-card reveal"><span class="mini-label">Official Contact</span><h3>connect@tuhitu.org</h3><p>+91 95996 61292<br>Gurgaon · Chandigarh · Pune<br>International contact: Dubai</p></aside></div></section>`,
  },
};

const aboutMenu = `
  <div class="nav-dropdown active">
    <button class="nav-dropdown-trigger active" type="button" aria-expanded="false" aria-controls="aboutMenu">About <i class="fa-solid fa-chevron-down" aria-hidden="true"></i></button>
    <div class="nav-dropdown-menu" id="aboutMenu"><a href="/about">About TuHiTu Club</a><a href="/about/our-model">Our Mission &amp; Model</a><a href="/about/impact">Impact &amp; Reach</a><a href="/about/stories">Stories &amp; Updates</a><a href="/about/governance">Governance &amp; Safeguarding</a></div>
  </div>`;

export function aboutPageResponse(key: AboutPageKey) {
  const page = pageContent[key];
  const html = `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>${page.title}</title><meta name="description" content="${page.description}"><meta name="theme-color" content="#0B1F3A"><meta name="codex-preview" content="development"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Poppins:wght@500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"><link rel="stylesheet" href="/css/style.css"></head>
  <body class="about-page about-${key}"><a class="skip-link" href="#main-content">Skip to main content</a><div class="topbar"><div class="container"><div class="topbar-info"><span><i class="fa-solid fa-calendar-check"></i> Registrations are open</span><a href="mailto:connect@tuhitu.org"><i class="fa-solid fa-envelope"></i> connect@tuhitu.org</a></div><div class="topbar-right"><select class="lang-select" id="langSelect" aria-label="Choose language"><option value="en">English</option><option value="hi">हिन्दी</option><option value="ar">العربية</option></select></div></div></div>
  <header class="site-header" id="siteHeader"><div class="container nav-wrap"><a href="/" class="brand" aria-label="TuHiTu Club Adopt an Elder home"><span class="mark"><img src="https://res.cloudinary.com/dfb2esugz/image/upload/v1787250614/Logo_1_qzasej.png" alt="TuHiTu Club logo" width="42" height="42" loading="eager" decoding="async"></span><span class="brand-text"><span>TuHiTu Club</span><span class="tagline">Adopt an Elder. Restore Dignity. Renew Hope.</span></span></a><nav class="main-nav" id="mainNav" aria-label="Primary navigation">${aboutMenu}<a href="/sponsor">Sponsor</a><a href="/partner-with-us">Partner With Us</a><a href="/?action=elder-registration">Register yourself</a><a href="/care-homes">Care Homes</a></nav><div class="header-actions"><a href="/volunteer" class="btn btn-ghost btn-sm"><i class="fa-solid fa-user-plus"></i><span>Become a Companion</span></a><span class="donate-action"><a href="/donate" class="btn btn-primary btn-sm"><i class="fa-solid fa-heart"></i><span>Donate</span></a><span class="tax-note"><i class="fa-solid fa-certificate"></i><span class="tax-label-full">80G Tax Benefit Available*</span><span class="tax-label-short">80G Available*</span></span></span><button class="nav-toggle" id="navToggle" aria-label="Toggle menu" aria-expanded="false"><i class="fa-solid fa-bars"></i></button></div></div></header><div class="nav-backdrop" id="navBackdrop"></div>
  <main id="main-content"><section class="about-hero"><div class="dot-grid"></div><div class="container"><nav class="breadcrumb" aria-label="Breadcrumb"><a href="/">Home</a><i class="fa-solid fa-chevron-right"></i><span>${page.eyebrow}</span></nav><div class="about-hero-copy reveal"><span class="eyebrow">${page.eyebrow}</span><h1>${page.heading}</h1><p>${page.intro}</p></div></div></section>${page.body}</main>
  <footer class="site-footer" id="contact"><div class="container"><div class="footer-grid"><div class="footer-brand"><a href="/" class="brand"><span class="mark"><img src="https://res.cloudinary.com/dfb2esugz/image/upload/v1787250614/Logo_1_qzasej.png" alt="TuHiTu Club logo" width="42" height="42" loading="lazy" decoding="async"></span><span class="brand-text"><span>TuHiTu Club</span></span></a><p>Adopt an Elder. Restore Dignity. Renew Hope.</p><div class="initiative-block"><span>An initiative by FDHS</span><img src="/images/fdhs-logo.png" alt="Federation of Digital Health Sciences" width="393" height="162"></div></div><div class="footer-col"><h4>About</h4><ul><li><a href="/about">About TuHiTu Club</a></li><li><a href="/about/our-model">Our Model</a></li><li><a href="/about/impact">Impact &amp; Reach</a></li><li><a href="/about/stories">Stories &amp; Updates</a></li><li><a href="/about/governance">Governance</a></li></ul></div><div class="footer-col"><h4>Get Involved</h4><ul><li><a href="/volunteer">Companion</a></li><li><a href="/sponsor">Sponsor</a></li><li><a href="/donate">Donate</a></li><li><a href="/partner-with-us">Partner With Us</a></li><li><a href="/?action=elder-registration">Register yourself</a></li><li><a href="/care-homes">Care Homes</a></li></ul></div><div class="footer-col footer-contact"><h4>Contact</h4><ul><li><i class="fa-solid fa-envelope"></i><a href="mailto:connect@tuhitu.org">connect@tuhitu.org</a></li><li><i class="fa-solid fa-phone"></i><a href="tel:+919599661292">+91 95996 61292</a></li><li><i class="fa-solid fa-location-dot"></i><span>Gurgaon · Chandigarh · Pune · Dubai</span></li></ul></div></div><div class="footer-compliance"><p><strong>Programme notice:</strong> Registration does not guarantee matching, approval, funding or participation.</p><p><strong>80G:</strong> Eligible Indian donations may qualify, subject to applicable law and a valid receipt.</p></div><div class="footer-bottom"><span>© 2026 TuHiTu Club. All rights reserved.</span><div class="legal-links"><a href="/about/governance#privacy">Privacy</a><a href="/about/governance#safeguarding">Safeguarding</a><a href="/about/governance#donations">Donation Policy</a><a href="/about/governance#grievance">Grievance</a></div></div></div></footer><button class="back-to-top" id="backToTop" aria-label="Back to top"><i class="fa-solid fa-arrow-up"></i></button><div class="toast" id="toast" role="status" aria-live="polite"><i class="fa-solid fa-circle-info"></i><span id="toastMsg"></span></div><script src="/js/script.js"></script><script src="/js/form.js"></script></body></html>`;

  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "cache-control": "public, max-age=0, must-revalidate", "x-content-type-options": "nosniff", "referrer-policy": "strict-origin-when-cross-origin" } });
}
